### ISSUE TITLE
Add link speed indicator (Windows)

### ISSUE THREAD

**Issue by Its5xq** [xornet-cloud/Reporter#14]
Checking user machine link speed is running at 1000Mbps or 100Mbps, then report the appropriate light for it.
Example:
![image](https://user-images.githubusercontent.com/85577277/150355794-6a6cc375-06b8-403a-b2fe-321d7cd2161f.png)

**Comment by Geoxor** [comment]
this is actually already planned (#6) whenever we figure out how to actually get that info

**Comment by N1kO23** [comment]
Implementation for linux is done
